[package]
name = "cesco-gpt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
async-openai = "0.17.1"
chrono = { version = "0.4.31", default-features = false, features = ["clock"]  }
clap = { version = "4.4.11", features = ["derive"] }
futures-util = "0.3.29"
log = "0.4.20"
pretty_env_logger = "0.5.0"
rustyline = "13.0.0"
serde = "1.0.193"
strum = "0.25.0"
strum_macros = "0.25.3"
teloxide = { version = "0.12.2", features = ["macros", "auto-send"] }
tokio = { version = "1.35.0", features = ["full"] }
tokio-stream = "0.1.14"
toml = "0.8.8"
